;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Item.UseArea.UncappingTable.Comb",NewTagName="Item.UseArea.UncappingTable.HoneyComb")
+GameplayTagList=(Tag="Item",DevComment="")
+GameplayTagList=(Tag="Item.BeeCarrier",DevComment="")
+GameplayTagList=(Tag="Item.Beehive",DevComment="")
+GameplayTagList=(Tag="Item.FocusFilter",DevComment="")
+GameplayTagList=(Tag="Item.FocusFilter.Beehive",DevComment="")
+GameplayTagList=(Tag="Item.FocusFilter.SwarmCluster",DevComment="")
+GameplayTagList=(Tag="Item.FocusFilter.UncappingTable",DevComment="")
+GameplayTagList=(Tag="Item.HoneyContainer",DevComment="")
+GameplayTagList=(Tag="Item.HoneyContainer.Source",DevComment="")
+GameplayTagList=(Tag="Item.HoneyContainer.Target",DevComment="")
+GameplayTagList=(Tag="Item.QueenCage",DevComment="")
+GameplayTagList=(Tag="Item.UseArea.Beehive.BeeBrush",DevComment="")
+GameplayTagList=(Tag="Item.UseArea.Beehive.Container",DevComment="")
+GameplayTagList=(Tag="Item.UseArea.Beehive.HoneyComb",DevComment="")
+GameplayTagList=(Tag="Item.UseArea.Beehive.PollenPatty",DevComment="")
+GameplayTagList=(Tag="Item.UseArea.Beehive.Smoker",DevComment="")
+GameplayTagList=(Tag="Item.UseArea.QueenBee.QueenCage",DevComment="")
+GameplayTagList=(Tag="Item.UseArea.SwarmCluster.BeeCarrier",DevComment="")
+GameplayTagList=(Tag="Item.UseArea.UncappingTable",DevComment="")
+GameplayTagList=(Tag="Item.UseArea.UncappingTable.CombWax",DevComment="")
+GameplayTagList=(Tag="Item.UseArea.UncappingTable.HoneyComb",DevComment="")
+GameplayTagList=(Tag="PartFocusAction",DevComment="")
+GameplayTagList=(Tag="PartFocusAction.Beehive.CombLift",DevComment="")
+GameplayTagList=(Tag="PartFocusAction.Beehive.LidOpen",DevComment="")

